# C-x [ -> open copy-mode (free cursor)
# C-SPC -> open selection mode in copy-mode
# Then M-w to copy things

unbind C-b
set -g prefix C-x
bind C-x send-prefix
set -g mode-keys emacs
set -g status-keys emacs
set -s escape-time 0
set -g mouse on
bind C-k kill-window
