[ui]
scale=1.5
font_path=/usr/share/fonts/TTF/IosevkaNerdFont-Regular.ttf
font_size_interface=16
font_size_code=18
layout=h(45,v(72,Source,Console),v(50,t(Stack,Files,Registers,Data,Thread),t(Watch,Breakpoints,Commands,Struct,Exe)))

; Gruber-Darker like Theme
[theme]
panel1=181818
panel2=181818
text=FFFFFF
textDisabled=787D81
border=404040
buttonNormal=202020
buttonHovered=4B5874
buttonPressed=262E40
buttonDisabled=1B1F23
textboxNormal=202020
textboxText=FFFFFF
textboxFocused=121414
codeFocused=3B3B3B
codeBackground=181818
codeDefault=FFFFFF
codeComment=CC8C3C
codeString=73C936
codeNumber=D3869B
codeOperator=FFDD33
codePreprocessor=95A99F
selected=3B3B3B
textSelected=FFFFFF
accent1=FF0000
accent2=00FF00
