;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-paren
        keyboard-escape-quit
        my-mc-mark-next
        my-mc-mark-prev
        ))

(setq mc/cmds-to-run-once
      '(
        ))
